---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jambfksl/public_html/
    - /bin/rm -rf $DEPLOYPATH # empty out deployment directory
    - /bin/cp -r * $DEPLOYPATH # copy source into public_html